#!/usr/bin/env bash
set -euo pipefail

if [ ! -e $1 ]; then
	echo "[error] $1 does not exist."
	return -1;
fi

i=1
while [ $i -lt 100 ]; do
	num=$i
	if [ $num -eq 1 ];then
		num=''
	fi

	if [ -e $1.bak$num ]; then
		i=$(( i + 1 ))	  
	else
		break;
	fi;
done

if [ $i -eq '1' ];then
	i=''
fi

cp -r $1 $1.bak$i


