#!/bin/bash

basename=$1                 # tex-file name
filename=${basename%.*}     # no suffix
filename_ls=${filename}-ls     # no suffix


cp ${filename}.tex ${filename_ls}.tex

cat ${filename_ls}.tex | \
    perl -pe 's/
\\documentclass\[(.*)\]\{(.*)\}/
\\documentclass\[$1, landscape\]\{$2\}/x' \
    | tee ${filename_ls}.tex > /dev/null

cat ${filename_ls}.tex \
    | perl -pe '
s/
\\setlength\{\\textwidth\}\{.*\}/
\\setlength\{\\textwidth\}\{260mm\}/x;
s/
\\setlength\{\\textheight\}\{.*\}/
\\setlength\{\\textheight\}\{180mm\}/x;' \
    | tee ${filename_ls}.tex > /dev/null


export TEXINPUTS=$TEXINPUTS:./:~/works/styles

if [ -f ${filename_ls}.tex ]; then
    if [ $(file ${filename_ls}.tex | grep UTF-8 | wc -l) -lt 1 ]; then
        echo '[ convert to UTF-8     ]'
        nkf -w --overwrite ${filename_ls}.tex
    else
        echo '[ check encode (UTF-8) ]'
    fi

    if [ -f /tmp/${filename_ls}.tex ]; then
        rm -f /tmp/${filename_ls}.tex
    fi
    cp ${filename_ls}.tex /tmp
    pushd . > /dev/null
    cd /tmp > /dev/null
    echo '[ generate tex -> dvi  ]'
    platex ${filename_ls}.tex      # tex -> dvi
else
    echo "file : '${filename_ls}.tex' does not exist."
    return
fi

if [ -f ${filename_ls}.dvi ]; then
    dvipdfmx -l ${filename_ls}.dvi 2> /dev/null   # dvi -> pdf
    echo '[ generate dvi -> pdf  ]'
else
    echo "file : '/tmp/${filename_ls}.dvi' does not exist."
    return
fi

if [ -f ${filename_ls}.pdf ]; then
    popd > /dev/null 2>&1
    rm -f ${filename_ls}.pdf 2> /dev/null
    cp /tmp/${filename_ls}.pdf ./
#   echo '[ open generated pdf   ]'
#   evince ${filename_ls}.pdf &  # open pdf
else
    echo "file : '/tmp/${filename_ls}.pdf' does not exist."
fi  
