#!/usr/bin/env perl
use v5.24;
use warnings;
use diagnostics;
use Time::Local;

my $path = '~/works/lab/fare/';

my $date    = shift // die 'fare <date> [year] [subject]';
my $year    = shift // qx'date --iso-8601 | perl -aF- -e \'print $F[0]\'';
my $subject = shift // 'astem';

my ($month, $day) = $date =~ /^(..)(..)/;
my $dow = get_dow($year, $month, $day);

# submit date
my ($s_day,$s_month,$s_year) = (localtime(time))[3..5];
$s_year += 1900;
$s_month += 1;
my $s_dow = get_dow($s_year, $s_month, $s_day);

my $basename = "$subject-$year$date";

system <<SCRIPT_END;
cd $path
cp template2.org $basename.org
LINE=\$(grep -n '期日' $basename.org | sed -e 's/:.*\$//g')
sed -e "\$LINE,\$LINE s/yyyy年/${year}年/" -i $basename.org
sed -e "\$LINE,\$LINE s/mm月/${month}月/"  -i $basename.org
sed -e "\$LINE,\$LINE s/dd日/${day}日/"    -i $basename.org
sed -e "\$LINE,\$LINE s/(dow)/(${dow})/"   -i $basename.org
LINE=\$(grep -n 'YYYY.*MM.*DD.*DOW' $basename.org | sed -e 's/:.*\$//g')
sed -e "\$LINE,\$LINE s/YYYY年/${s_year}年/" -i $basename.org
sed -e "\$LINE,\$LINE s/MM月/${s_month}月/"  -i $basename.org
sed -e "\$LINE,\$LINE s/DD日/${s_day}日/"    -i $basename.org
sed -e "\$LINE,\$LINE s/(DOW)/(${s_dow})/"   -i $basename.org
org2tex $basename.org
tex2pdf $basename.tex
evince  $basename.pdf
SCRIPT_END


sub get_dow {
  my ($year, $month, $day) = @_;
  my $dow = (localtime( timelocal(0, 0, 0, $day, $month - 1, $year) ))[6];
  return ("日","月","火","水","木","金","土")[$dow];
}
