#!/usr/bin/env perl
use v5.24;
use warnings;

use Getopt::Kingpin;

my $kingpin = Getopt::Kingpin->new();
my $f_upload = $kingpin->flag('upload', 'upload to archive')->short('u')->bool;
my $date     = $kingpin->arg('date', '')->default(qx/date --iso-8601 | perl -pe 's|\n||'/);

$kingpin->parse;


if ( $f_upload ) {
  my $file = $date . "-hls-oosako.pdf";
  system <<EOF;
cd ~/works/lab/report
archive.pl HLS/LATEST/ -u $file
EOF
}
else {
  my $file = $date . "-hls-oosako.org";

  system <<EOF;
cd ~/works/lab/report
emacsclient -n $file
EOF

}
